### ISSUE TITLE
Incorrect commands to build project in ui.sh

### ISSUE THREAD

**Issue by Mehul-Kumar-27** [honeynet/riotpot#43]
In the ui.sh the build function to build the ui contains the script as 

```
function riotpot::ui::build(){
    npm install react-scripts --silent
    npm install ui --silent
    npm --prefix="ui" --omit="dev" run build 
}
```
I think this is probably wrong as the correct command should have been first installing the dependencies and then running the npm build command inside the ui folder. After running the present command we get a node_modules folder and the package.json, (which contains the unwanted ui package) file in the root directory.

**Comment by RicYaben** [comment]
This is the intended behavior :)

**Comment by Mehul-Kumar-27** [comment]
@RicYaben , Sir, thank you for reviewing the PR. I am looking forward to contributing to this project in GSoC'24. Could you please provide me with the means to connect with you? I tried searching for you on Discord but was unable to find you.

Actually, I have some doubts and would like to know what things you would like to add or improve during GSoC'24.

Thank you for your time.

Best Regards,
Mehul Kumar
